/*
 * Generated by dtrace(1M).
 */

#ifndef	_SNOW_PROVIDER_H
#define	_SNOW_PROVIDER_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define SNOWPROBE_STABILITY "___dtrace_stability$SnowProbe$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define SNOWPROBE_TYPEDEFS "___dtrace_typedefs$SnowProbe$v2"

#define	SNOWPROBE_GC() \
do { \
	__asm__ volatile(".reference " SNOWPROBE_TYPEDEFS); \
	__dtrace_probe$SnowProbe$gc$v1(); \
	__asm__ volatile(".reference " SNOWPROBE_STABILITY); \
} while (0)
#define	SNOWPROBE_GC_ENABLED() \
	__dtrace_isenabled$SnowProbe$gc$v1()
#define	SNOWPROBE_GC_ALLOC(arg0) \
do { \
	__asm__ volatile(".reference " SNOWPROBE_TYPEDEFS); \
	__dtrace_probe$SnowProbe$gc_alloc$v1$75696e7436345f74(arg0); \
	__asm__ volatile(".reference " SNOWPROBE_STABILITY); \
} while (0)
#define	SNOWPROBE_GC_ALLOC_ENABLED() \
	__dtrace_isenabled$SnowProbe$gc_alloc$v1()
#define	SNOWPROBE_GC_FINISHED(arg0, arg1) \
do { \
	__asm__ volatile(".reference " SNOWPROBE_TYPEDEFS); \
	__dtrace_probe$SnowProbe$gc_finished$v1$75696e7436345f74$696e7436345f74(arg0, arg1); \
	__asm__ volatile(".reference " SNOWPROBE_STABILITY); \
} while (0)
#define	SNOWPROBE_GC_FINISHED_ENABLED() \
	__dtrace_isenabled$SnowProbe$gc_finished$v1()
#define	SNOWPROBE_GC_MAJOR() \
do { \
	__asm__ volatile(".reference " SNOWPROBE_TYPEDEFS); \
	__dtrace_probe$SnowProbe$gc_major$v1(); \
	__asm__ volatile(".reference " SNOWPROBE_STABILITY); \
} while (0)
#define	SNOWPROBE_GC_MAJOR_ENABLED() \
	__dtrace_isenabled$SnowProbe$gc_major$v1()
#define	SNOWPROBE_GC_MINOR() \
do { \
	__asm__ volatile(".reference " SNOWPROBE_TYPEDEFS); \
	__dtrace_probe$SnowProbe$gc_minor$v1(); \
	__asm__ volatile(".reference " SNOWPROBE_STABILITY); \
} while (0)
#define	SNOWPROBE_GC_MINOR_ENABLED() \
	__dtrace_isenabled$SnowProbe$gc_minor$v1()


extern void __dtrace_probe$SnowProbe$gc$v1(void);
extern int __dtrace_isenabled$SnowProbe$gc$v1(void);
extern void __dtrace_probe$SnowProbe$gc_alloc$v1$75696e7436345f74(uint64_t);
extern int __dtrace_isenabled$SnowProbe$gc_alloc$v1(void);
extern void __dtrace_probe$SnowProbe$gc_finished$v1$75696e7436345f74$696e7436345f74(uint64_t, int64_t);
extern int __dtrace_isenabled$SnowProbe$gc_finished$v1(void);
extern void __dtrace_probe$SnowProbe$gc_major$v1(void);
extern int __dtrace_isenabled$SnowProbe$gc_major$v1(void);
extern void __dtrace_probe$SnowProbe$gc_minor$v1(void);
extern int __dtrace_isenabled$SnowProbe$gc_minor$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _SNOW_PROVIDER_H */
